// Generated by tools/gen_quest_objectives.py.
namespace Godswar.Server.Domain.World.Content;
internal static class QuestUnresolvedRequirements
{
    internal static readonly HashSet<uint> QuestIds = [151u, 410u, 411u, 414u, 456u, 467u, 510u, 599u, 607u, 656u, 1151u, 1212u, 1220u, 1456u, 1467u, 1508u, 1510u, 1599u, 1607u, 1656u];
}
