// Generated by tools/gen_quest_runtime_requirements.py.
namespace Godswar.Server.Domain.World.Content;

internal static class StarterQuestCollectObjectives
{
    internal readonly record struct CollectObjective(uint ItemId, int Required, string DisplayName = "任务道具");
    public static IReadOnlyDictionary<uint, CollectObjective> ByQuestId { get; } =
        new Dictionary<uint, CollectObjective>
        {
            [75u] = new(507u, 10, "薄荷种子"),
            [83u] = new(508u, 1, "绿石片"),
            [87u] = new(509u, 10, "小钱包"),
            [115u] = new(520u, 1, "魔法海龟壳"),
            [146u] = new(523u, 12, "狮子尾巴"),
            [147u] = new(0u, 12, "珠子"),
            [148u] = new(525u, 1, "射手武器"),
            [149u] = new(0u, 1, "地毯"),
            [151u] = new(0u, 10, "木料"),
            [152u] = new(0u, 10, "零件"),
            [162u] = new(531u, 1, "魔法重型盔甲"),
            [323u] = new(0u, 10, "法杖"),
            [325u] = new(0u, 10, "教杖"),
            [362u] = new(0u, 10, "祭杖"),
            [411u] = new(0u, 10, "遗失的戒指"),
            [475u] = new(0u, 10, "神杖"),
            [526u] = new(400u, 5, "蛇尾"),
            [553u] = new(402u, 10, "骨头"),
            [557u] = new(403u, 10, "蛇牙"),
            [559u] = new(404u, 1, "蜘蛛丝"),
            [561u] = new(405u, 10, "诅咒的遗物"),
            [562u] = new(406u, 10, "骨头碎片"),
            [567u] = new(0u, 10, "美酒"),
            [599u] = new(0u, 10, "不死生物样本"),
            [1075u] = new(107u, 1, "柳树种子"),
            [1083u] = new(108u, 1, "琥珀碎片"),
            [1087u] = new(109u, 1, "近战装备"),
            [1115u] = new(120u, 1, "玉杯"),
            [1146u] = new(123u, 10, "野猪的獠牙"),
            [1147u] = new(0u, 12, "珠子"),
            [1148u] = new(125u, 1, "塔塔罗斯之锤"),
            [1149u] = new(0u, 1, "地毯"),
            [1151u] = new(0u, 10, "木料"),
            [1152u] = new(128u, 10, "鹿角"),
            [1162u] = new(0u, 10, "牙齿"),
            [1323u] = new(0u, 10, "法杖"),
            [1325u] = new(0u, 10, "神杖"),
            [1362u] = new(0u, 10, "祭杖"),
            [1411u] = new(0u, 10, "遗失的戒指"),
            [1475u] = new(0u, 10, "神杖"),
            [1526u] = new(300u, 5, "蜂巢"),
            [1528u] = new(301u, 8, "蛇牙"),
            [1557u] = new(303u, 10, "鹿角"),
            [1561u] = new(305u, 10, "腐败的蹄子"),
            [1562u] = new(306u, 10, "鳄鱼牙齿"),
            [1563u] = new(307u, 10, "狼牙"),
            [1567u] = new(0u, 10, "美酒"),
            [1599u] = new(0u, 10, "不死生物样本"),
        };
    public static bool TryGet(uint questId, out CollectObjective objective) =>
        ByQuestId.TryGetValue(questId, out objective);
}
