using System.Text;
using System.Text.RegularExpressions;

namespace Godswar.Server.Domain.World.Content;

/// <summary>
/// One thing a quest asks the player to kill, and how many of them.
/// </summary>
/// <remarks>
/// <paramref name="MonsterId"/> is the client's own id from
/// Text/QuestMonster.dat, which is what the frames that drive the quest
/// window carry. The map and coordinates are the position the client
/// shows for the target, used when the name cannot be resolved.
/// <para>
/// <paramref name="Match"/> is the name the client's monster table
/// gives that id, and is only set when the quest text calls the target
/// something else - quest 528 asks for eight "Fake Treasures" while the
/// world carries them as "Juno's Box" (id 1023). A kill is credited on
/// this name when there is one, otherwise on the quest text.
/// </para>
/// </remarks>
internal readonly record struct QuestObjective(
    string Target,
    string Match,
    int Required,
    uint MonsterId,
    uint MapId,
    float X,
    float Z);

/// <summary>
/// The newbie chain's kill objectives, read from the client's own quest
/// text (Text/Quest/&lt;id&gt;.dat) and Quest.xml.
/// </summary>
/// <remarks>
/// Generated by <c>tools/gen_quest_objectives.py</c>; do not edit by
/// hand. A quest that is absent here has no objective this server can
/// verify - a plain talk quest, or one that only asks for items - and is
/// therefore handed in as soon as the player asks.
/// <para>
/// Progress is stored as up to four counters packed into the single
/// progress integer of the character's quest row, because a quest can
/// name up to three targets.
/// </para>
/// </remarks>
internal static partial class StarterQuestObjectives
{
    /// <summary>Bits one objective counter occupies.</summary>
    public const int CounterBits = 16;

    /// <summary>How many objectives one quest can track.</summary>
    public const int CounterSlots = 4;

    /// <summary>Largest count a slot can hold.</summary>
    public const int CounterMaximum = short.MaxValue;

    /// <summary>How close a kill has to be when the name is unknown.</summary>
    public const float MatchRadius = 40.0f;

    public static IReadOnlyDictionary<uint, QuestObjective[]> ByQuestId
        { get; } = new Dictionary<uint, QuestObjective[]>
        {
            [70u] = [new QuestObjective("Wild Lions", "", 1, 1061u, 5u, -54.0f, -11.0f)],
            [75u] = [new QuestObjective("Wizards", "", 1, 1062u, 5u, 1.0f, 1.0f)],
            [80u] = [new QuestObjective("Forest Wizards", "", 1, 1065u, 5u, 144.0f, -97.0f)],
            [87u] = [new QuestObjective("Robber Kelins", "", 1, 1081u, 16u, 1.0f, 1.0f)],
            [93u] = [new QuestObjective("Magic Tortoise", "", 80, 1082u, 16u, -200.0f, 4.0f)],
            [95u] = [new QuestObjective("Red Deer", "", 100, 1084u, 16u, -45.0f, -24.0f)],
            [97u] = [new QuestObjective("Skeleton Mage", "", 100, 1085u, 16u, -148.0f, 16.0f)],
            [100u] = [new QuestObjective("Deigo Pirates", "", 1, 1101u, 15u, 5.0f, 42.0f)],
            [104u] = [new QuestObjective("Red Deer", "", 1, 1084u, 16u, -45.0f, -24.0f)],
            [105u] = [new QuestObjective("Deigo Pirates", "", 1, 1101u, 15u, 5.0f, 42.0f)],
            [106u] = [new QuestObjective("Persian Missionaries from Derveni", "", 1, 1104u, 15u, 157.0f, -20.0f)],
            [110u] = [new QuestObjective("Forest Wizards", "", 1, 1065u, 5u, 144.0f, -97.0f)],
            [112u] = [new QuestObjective("Amazon Fighters", "", 80, 1083u, 16u, 62.0f, -5.0f)],
            [118u] = [new QuestObjective("Astrien", "", 1, 1063u, 5u, 51.0f, -133.0f)],
            [119u] = [new QuestObjective("Death Servants", "", 1, 1080u, 16u, -2.0f, -163.0f)],
            [120u] = [new QuestObjective("Robber Kelin", "", 10, 1081u, 16u, -95.0f, -138.0f)],
            [121u] = [new QuestObjective("Centaur", "", 100, 3007u, 15u, 102.0f, 127.0f)],
            [122u] = [new QuestObjective("Centaur Sheikh Hailer", "", 1, 3007u, 15u, 185.0f, 62.0f)],
            [143u] = [new QuestObjective("Skeleton Mages", "", 80, 1085u, 16u, -148.0f, 16.0f)],
            [144u] = [new QuestObjective("Jaba Astrologist", "", 100, 1118u, 17u, 26.0f, 40.0f)],
            [158u] = [new QuestObjective("Plain Wolf", "", 100, 1060u, 5u, -20.0f, -168.0f)],
            [159u] = [new QuestObjective("Wizard", "", 100, 1062u, 5u, -148.0f, -19.0f)],
            [160u] = [new QuestObjective("Amazon Scout", "", 100, 1064u, 5u, -160.0f, 100.0f)],
            [161u] = [new QuestObjective("Robber Kelin", "", 100, 1081u, 16u, -95.0f, -138.0f)],
            [163u] = [new QuestObjective("Amazon Fighters", "", 80, 1083u, 16u, 62.0f, -5.0f)],
            [164u] = [new QuestObjective("Red Deer", "", 80, 1084u, 16u, -45.0f, -24.0f)],
            [165u] = [new QuestObjective("Giant Boa", "", 100, 1100u, 15u, 59.0f, 175.0f)],
            [166u] = [new QuestObjective("Centaur", "", 100, 3007u, 15u, 102.0f, 127.0f)],
            [167u] = [new QuestObjective("Illyria Brigand", "", 100, 1091u, 19u, 0.0f, -82.0f)],
            [168u] = [new QuestObjective("Scholar Kal", "", 100, 1094u, 19u, 102.0f, 66.0f)],
            [172u] = [new QuestObjective("Little Weird Bird", "", 100, 1110u, 17u, 94.0f, -188.0f)],
            [173u] = [new QuestObjective("Forest Magicians on the Isthmus of Corinth", "", 1, 1111u, 17u, 19.0f, -196.0f)],
            [174u] = [new QuestObjective("Harpy's Underlings", "", 1, 1112u, 17u, -133.0f, -201.0f)],
            [175u] = [new QuestObjective("Elf's Servant", "", 100, 1113u, 17u, -52.0f, -191.0f)],
            [176u] = [new QuestObjective("Bronze Lions", "", 1, 1114u, 17u, -162.0f, 37.0f)],
            [177u] = [new QuestObjective("Boa", "", 100, 1031u, 17u, -37.0f, -101.0f), new QuestObjective("Boa", "", 100, 1046u, 17u, -37.0f, -101.0f)],
            [179u] = [new QuestObjective("Athenian Patrolman", "", 100, 1077u, 19u, -78.0f, -59.0f)],
            [180u] = [new QuestObjective("Athenian Raider", "", 100, 1078u, 19u, -8.0f, -140.0f)],
            [182u] = [new QuestObjective("Forest Warrior", "", 100, 1067u, 5u, 200.0f, -40.0f)],
            [185u] = [new QuestObjective("Dumb Wood Men", "", 1, 1027u, 0u, 186.0f, -2.0f)],
            [192u] = [new QuestObjective("Snake", "", 8, 1015u, 0u, 164.0f, 170.0f), new QuestObjective("Snake", "", 8, 1029u, 0u, 164.0f, 170.0f)],
            [200u] = [new QuestObjective("Wizard", "", 100, 1062u, 5u, -148.0f, -19.0f)],
            [201u] = [new QuestObjective("Huge Frog", "", 100, 1066u, 5u, 60.0f, 40.0f)],
            [202u] = [new QuestObjective("Robber Kelin", "", 10, 1081u, 16u, -95.0f, -138.0f)],
            [203u] = [new QuestObjective("Red Deer", "", 100, 1084u, 16u, -45.0f, -24.0f)],
            [204u] = [new QuestObjective("Corinthian Boa", "", 100, 1115u, 17u, 4.0f, -65.0f)],
            [205u] = [new QuestObjective("Milier Guardsman", "", 100, 1117u, 17u, 188.0f, -43.0f)],
            [206u] = [new QuestObjective("Harpy", "", 100, 1106u, 15u, -27.0f, -76.0f)],
            [210u] = [new QuestObjective("Woodland Wolf", "", 20, 1431u, 4u, 202.0f, -200.0f)],
            [211u] = [new QuestObjective("Huge Scorpion", "", 35, 1040u, 13u, 118.0f, -19.0f)],
            [212u] = [new QuestObjective("Dark Wizard", "", 100, 1045u, 13u, -175.0f, 68.0f), new QuestObjective("Dark Wizard", "", 100, 1055u, 13u, -175.0f, 68.0f)],
            [217u] = [new QuestObjective("Dark Spirit Yones", "", 1, 9061u, 16u, 40.0f, -200.0f)],
            [220u] = [new QuestObjective("Valkyr", "", 80, 9064u, 16u, 62.0f, -5.0f)],
            [221u] = [new QuestObjective("Beast Master Leader Cassirer", "", 1, 1086u, 16u, 186.0f, 76.0f)],
            [227u] = [new QuestObjective("Huge Frog", "", 100, 1066u, 5u, 60.0f, 40.0f)],
            [228u] = [new QuestObjective("Magic Tortoise", "", 10, 1082u, 16u, -200.0f, 4.0f)],
            [229u] = [new QuestObjective("Deigo Pirate", "", 100, 1101u, 15u, 5.0f, 42.0f)],
            [230u] = [new QuestObjective("Harpy", "", 100, 1106u, 15u, -27.0f, -76.0f)],
            [233u] = [new QuestObjective("Wild Lion", "", 100, 1061u, 5u, -54.0f, -11.0f)],
            [235u] = [new QuestObjective("Plains Wolves", "", 1, 1060u, 5u, -20.0f, -168.0f)],
            [236u] = [new QuestObjective("Huge Frogs", "", 1, 1066u, 5u, 60.0f, 40.0f)],
            [238u] = [new QuestObjective("Hero Chipa", "", 1, 9043u, 5u, -200.0f, 200.0f)],
            [239u] = [new QuestObjective("Wizard Balthazar", "", 1, 1062u, 5u, 218.0f, -147.0f)],
            [240u] = [new QuestObjective("Wolf King Astrien with a group of friends", "", 1, 1063u, 5u, 51.0f, -133.0f)],
            [242u] = [new QuestObjective("Death Servants", "", 1, 1080u, 16u, -2.0f, -163.0f)],
            [243u] = [new QuestObjective("Robber Kelins", "", 1, 1081u, 16u, -95.0f, -138.0f)],
            [244u] = [new QuestObjective("Amazon Warriors", "", 1, 0u, 16u, 62.0f, -5.0f)],
            [245u] = [new QuestObjective("Red Deer along the Argolis Coast", "", 1, 1084u, 16u, -45.0f, -24.0f)],
            [246u] = [new QuestObjective("Skeleton Mages along the Argolis Coast", "", 1, 1020u, 16u, -148.0f, 16.0f)],
            [247u] = [new QuestObjective("Deigo Pirate", "", 100, 1101u, 15u, 5.0f, 42.0f)],
            [249u] = [new QuestObjective("Persian Spy", "", 10, 1432u, 4u, 80.0f, -158.0f)],
            [250u] = [new QuestObjective("Huge Skeleton", "", 40, 1043u, 13u, 99.0f, 139.0f)],
            [251u] = [new QuestObjective("Wizard", "", 100, 1062u, 5u, -148.0f, -19.0f)],
            [252u] = [new QuestObjective("Huge Frog", "", 100, 1066u, 5u, 60.0f, 40.0f)],
            [253u] = [new QuestObjective("Death Servant", "", 10, 1080u, 16u, -2.0f, -163.0f)],
            [254u] = [new QuestObjective("Magic Tortoise", "", 100, 1082u, 16u, -200.0f, 4.0f)],
            [255u] = [new QuestObjective("Giant Boa", "", 100, 1100u, 15u, 59.0f, 175.0f)],
            [256u] = [new QuestObjective("Centaur", "", 100, 3007u, 15u, 102.0f, 127.0f)],
            [257u] = [new QuestObjective("Persian Missionary", "", 100, 1104u, 15u, 157.0f, -20.0f)],
            [258u] = [new QuestObjective("Harpy", "", 100, 1106u, 15u, -27.0f, -76.0f)],
            [260u] = [new QuestObjective("Wizard", "", 100, 1062u, 13u, -133.0f, -55.0f)],
            [261u] = [new QuestObjective("Huge Frog", "", 100, 1066u, 5u, 60.0f, 40.0f)],
            [262u] = [new QuestObjective("Magic Tortoise", "", 80, 1082u, 16u, -200.0f, 4.0f)],
            [263u] = [new QuestObjective("Centaur", "", 100, 3007u, 15u, 102.0f, 127.0f)],
            [292u] = [new QuestObjective("Sicilian Elves", "", 100, 5160u, 32u, -141.0f, -170.0f)],
            [293u] = [new QuestObjective("Numb Wolves", "", 100, 5161u, 32u, -102.0f, -120.0f)],
            [294u] = [new QuestObjective("Ruthless Puppets", "", 100, 5162u, 32u, -89.0f, 9.0f)],
            [295u] = [new QuestObjective("Blaze Vipers", "", 100, 5163u, 32u, -155.0f, 21.0f)],
            [296u] = [new QuestObjective("Ice Wraiths", "", 100, 5165u, 32u, -30.0f, -20.0f)],
            [297u] = [new QuestObjective("Gela Guards", "", 100, 5166u, 32u, -177.0f, 159.0f)],
            [298u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, -82.0f, 155.0f)],
            [300u] = [new QuestObjective("Forest Warriors", "", 50, 1067u, 5u, 200.0f, -40.0f)],
            [306u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, -82.0f, 155.0f)],
            [307u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 15u, 90.0f, -156.0f)],
            [308u] = [new QuestObjective("Ancient Crocodiles", "", 100, 1107u, 15u, -105.0f, 114.0f)],
            [309u] = [new QuestObjective("Persian Missionaries", "", 1, 1104u, 15u, 157.0f, -20.0f)],
            [310u] = [new QuestObjective("Harpies", "", 1, 1106u, 15u, -27.0f, -76.0f)],
            [315u] = [new QuestObjective("Mutant Cruces", "", 100, 5290u, 32u, -50.0f, -150.0f)],
            [316u] = [new QuestObjective("Wicked Alex", "", 100, 5291u, 32u, -66.0f, 0.0f)],
            [317u] = [new QuestObjective("Skeleton Captain Ixion", "", 100, 5292u, 32u, -169.0f, 160.0f)],
            [319u] = [new QuestObjective("Harpies", "", 1, 1106u, 15u, -27.0f, -76.0f)],
            [320u] = [new QuestObjective("Wasp", "", 10, 1014u, 13u, 183.0f, -51.0f)],
            [321u] = [new QuestObjective("Undead Fighter", "", 10, 1444u, 4u, -145.0f, 172.0f)],
            [322u] = [new QuestObjective("Forest Warrior", "", 100, 1067u, 5u, 200.0f, -40.0f)],
            [324u] = [new QuestObjective("Centaur", "", 100, 3007u, 15u, 102.0f, 127.0f)],
            [326u] = [new QuestObjective("Ferocious Wolf", "", 10, 1024u, 5u, 51.0f, -133.0f)],
            [330u] = [new QuestObjective("Bloodfly Wasps", "", 1, 2001u, 14u, 149.0f, -39.0f)],
            [331u] = [new QuestObjective("Female Acadian Warrior", "", 100, 2004u, 14u, 67.0f, -59.0f)],
            [332u] = [new QuestObjective("those Jungle Minotaurs", "", 1, 2010u, 14u, -110.0f, 92.0f)],
            [333u] = [new QuestObjective("Bloodfly Wasps!", "", 1, 2001u, 14u, 149.0f, -39.0f)],
            [334u] = [new QuestObjective("Spider Warriors", "", 1, 2002u, 14u, 152.0f, -188.0f)],
            [335u] = [new QuestObjective("Totem Spider", "", 100, 2003u, 14u, 191.0f, 73.0f)],
            [336u] = [new QuestObjective("Frontline Cavalries", "", 1, 2006u, 14u, 72.0f, 126.0f)],
            [337u] = [new QuestObjective("Forest Lion", "", 100, 2005u, 14u, 24.0f, -126.0f)],
            [338u] = [new QuestObjective("Frontline Priests", "", 1, 2009u, 14u, -163.0f, 134.0f)],
            [339u] = [new QuestObjective("Jungle Minotaurs", "", 1, 2010u, 14u, -110.0f, 92.0f)],
            [340u] = [new QuestObjective("Purple Winged Demons", "", 1, 2011u, 14u, -202.0f, -16.0f)],
            [341u] = [new QuestObjective("Tree Demons", "", 1, 2007u, 14u, -176.0f, -213.0f)],
            [343u] = [new QuestObjective("Bloodfly Wasp", "", 80, 2001u, 14u, 149.0f, -39.0f)],
            [347u] = [new QuestObjective("Spider Warriors", "", 1, 2002u, 14u, 152.0f, -188.0f)],
            [351u] = [new QuestObjective("Purple Winged Demons", "", 1, 2011u, 14u, -202.0f, -16.0f)],
            [353u] = [new QuestObjective("Abyss Demons", "", 1, 2015u, 14u, -169.0f, -49.0f)],
            [354u] = [new QuestObjective("Persian Mages", "", 1, 3036u, 8u, -1.0f, -158.0f)],
            [355u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [356u] = [new QuestObjective("Persian Archmages", "", 1, 3020u, 8u, -118.0f, 57.0f)],
            [357u] = [new QuestObjective("Rot Hide Cooers", "", 1, 3033u, 8u, -13.0f, -84.0f)],
            [358u] = [new QuestObjective("White Cooers", "", 1, 3034u, 8u, -13.0f, -84.0f)],
            [359u] = [new QuestObjective("Flaming Hounds", "", 1, 3024u, 8u, 19.0f, -5.0f)],
            [360u] = [new QuestObjective("Persian Huntresses", "", 1, 3025u, 8u, 18.0f, 71.0f)],
            [361u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [362u] = [new QuestObjective("Persian Whiterobe Mages to get their wand", "", 1, 3032u, 8u, 1.0f, 1.0f)],
            [363u] = [new QuestObjective("Persian Clergies", "", 1, 3005u, 8u, 102.0f, 168.0f)],
            [364u] = [new QuestObjective("Persian Scouts", "", 1, 1095u, 8u, 182.0f, 127.0f)],
            [365u] = [new QuestObjective("Persian Soldiers", "", 1, 3022u, 8u, -18.0f, 113.0f)],
            [366u] = [new QuestObjective("Persian Bowyers", "", 1, 3023u, 8u, -14.0f, 148.0f)],
            [367u] = [new QuestObjective("Persian Archmages", "", 1, 3020u, 8u, -118.0f, 57.0f)],
            [368u] = [new QuestObjective("Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [370u] = [new QuestObjective("Persian Whiterobe Mages", "", 1, 3032u, 8u, 72.0f, 107.0f)],
            [374u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, -1.0f, -158.0f)],
            [376u] = [new QuestObjective("Persian Captain", "", 1, 3038u, 8u, -70.0f, 165.0f)],
            [380u] = [new QuestObjective("all of the Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [382u] = [new QuestObjective("Mardonius", "", 1, 3030u, 8u, -184.0f, 32.0f)],
            [386u] = [new QuestObjective("Skeleton Warlock", "", 100, 1075u, 17u, 170.0f, -88.0f)],
            [387u] = [new QuestObjective("Skeleton Warlock", "", 100, 1075u, 18u, 154.0f, -41.0f)],
            [388u] = [new QuestObjective("Young Red Dragons", "", 1, 1119u, 17u, -177.0f, -82.0f)],
            [393u] = [new QuestObjective("Persian Mages", "", 1, 3036u, 8u, -1.0f, -154.0f)],
            [394u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, -1.0f, -154.0f)],
            [408u] = [new QuestObjective("Wizard", "", 10, 1062u, 5u, 218.0f, -147.0f)],
            [409u] = [new QuestObjective("Forest Wizard", "", 50, 1065u, 5u, 144.0f, -97.0f)],
            [412u] = [new QuestObjective("Boa", "", 50, 1031u, 13u, 192.0f, -166.0f), new QuestObjective("Boa", "", 50, 1046u, 13u, 192.0f, -166.0f)],
            [413u] = [new QuestObjective("Hero Chipa", "", 10, 9043u, 5u, -200.0f, 200.0f)],
            [415u] = [new QuestObjective("Forest Magician", "", 30, 1111u, 17u, 19.0f, -196.0f)],
            [416u] = [new QuestObjective("Astrien", "", 10, 1063u, 5u, 51.0f, -133.0f)],
            [417u] = [new QuestObjective("Gordon", "", 10, 1026u, 4u, -181.0f, 154.0f)],
            [418u] = [new QuestObjective("Woodland Wolf", "", 10, 1431u, 4u, 202.0f, -200.0f)],
            [419u] = [new QuestObjective("Wild Lion", "", 30, 1061u, 5u, -54.0f, -11.0f)],
            [421u] = [new QuestObjective("Death Servant", "", 50, 1080u, 16u, -2.0f, -163.0f)],
            [422u] = [new QuestObjective("Robber Kelin", "", 10, 1081u, 16u, -95.0f, -138.0f)],
            [423u] = [new QuestObjective("Little Weird Bird", "", 30, 1110u, 17u, 94.0f, -188.0f)],
            [424u] = [new QuestObjective("Amazon Fighters", "", 10, 1083u, 16u, 62.0f, -5.0f)],
            [425u] = [new QuestObjective("Red Deer", "", 10, 1084u, 16u, -45.0f, -24.0f)],
            [426u] = [new QuestObjective("Skeleton Mage", "", 10, 1085u, 16u, -148.0f, 16.0f)],
            [427u] = [new QuestObjective("Huge Frog", "", 50, 1066u, 5u, 60.0f, 40.0f)],
            [428u] = [new QuestObjective("Wizard", "", 30, 1062u, 5u, -148.0f, -19.0f)],
            [429u] = [new QuestObjective("Animated Axe", "", 40, 1445u, 4u, -110.0f, -56.0f)],
            [430u] = [new QuestObjective("Green Snake", "", 10, 1487u, 0u, 188.0f, 111.0f)],
            [431u] = [new QuestObjective("Silver Tail Scorpion", "", 10, 1485u, 0u, 186.0f, 8.0f)],
            [432u] = [new QuestObjective("Skeleton Mage", "", 50, 1085u, 16u, -148.0f, 16.0f)],
            [434u] = [new QuestObjective("Harpy", "", 40, 1106u, 17u, -133.0f, -201.0f)],
            [435u] = [new QuestObjective("Huge Skeleton", "", 30, 1043u, 13u, 110.0f, -131.0f)],
            [436u] = [new QuestObjective("Wasp", "", 10, 1014u, 13u, 183.0f, -51.0f)],
            [438u] = [new QuestObjective("Forest Warrior", "", 40, 1067u, 5u, 200.0f, -40.0f)],
            [439u] = [new QuestObjective("Giant Boa", "", 20, 1100u, 15u, 59.0f, 175.0f)],
            [440u] = [new QuestObjective("Magic Tortoise", "", 50, 1082u, 16u, -200.0f, 4.0f)],
            [441u] = [new QuestObjective("Suburban Scorpion", "", 10, 1435u, 4u, 9.0f, -45.0f)],
            [442u] = [new QuestObjective("Peninsula Bandit", "", 10, 1433u, 4u, 163.0f, -76.0f)],
            [445u] = [new QuestObjective("Huge Scorpion", "", 20, 1040u, 13u, 118.0f, -19.0f)],
            [446u] = [new QuestObjective("Dark Wizard", "", 10, 1045u, 13u, -175.0f, 68.0f), new QuestObjective("Dark Wizard", "", 10, 1055u, 13u, -175.0f, 68.0f)],
            [447u] = [new QuestObjective("Centauri Heathen", "", 10, 5060u, 29u, -132.0f, -207.0f)],
            [457u] = [new QuestObjective("Persian Spy", "", 500, 1432u, 4u, 80.0f, -158.0f)],
            [458u] = [new QuestObjective("Huge Skeleton", "", 500, 1043u, 13u, 99.0f, 139.0f)],
            [459u] = [new QuestObjective("Wizard", "", 500, 1062u, 5u, -148.0f, -19.0f)],
            [460u] = [new QuestObjective("Huge Frog", "", 500, 1066u, 5u, 60.0f, 40.0f)],
            [461u] = [new QuestObjective("Death Servant", "", 500, 1080u, 16u, -2.0f, -163.0f)],
            [462u] = [new QuestObjective("Magic Tortoise", "", 500, 1082u, 16u, -200.0f, 4.0f)],
            [463u] = [new QuestObjective("Giant Boa", "", 500, 1100u, 15u, 59.0f, 175.0f)],
            [464u] = [new QuestObjective("Centaur", "", 500, 3007u, 15u, 102.0f, 127.0f)],
            [465u] = [new QuestObjective("Persian Missionary", "", 500, 1104u, 15u, 157.0f, -20.0f)],
            [466u] = [new QuestObjective("Harpy", "", 500, 1106u, 15u, -27.0f, -76.0f)],
            [474u] = [new QuestObjective("White Cooer", "", 50, 3034u, 8u, -30.0f, -36.0f), new QuestObjective("Rot Hide Cooer", "", 50, 3033u, 8u, -30.0f, -36.0f)],
            [508u] = [new QuestObjective("Amazon Scout", "", 100, 1064u, 5u, 1.0f, 1.0f)],
            [509u] = [new QuestObjective("Robber Kelin", "", 10, 1081u, 16u, 1.0f, 1.0f)],
            [511u] = [new QuestObjective("Centaur Warrior", "", 100, 1102u, 15u, 1.0f, 1.0f)],
            [512u] = [new QuestObjective("Persian Huntress", "", 100, 3025u, 8u, 1.0f, 1.0f)],
            [513u] = [new QuestObjective("Forest Warrior", "", 100, 1067u, 5u, 153.0f, 130.0f)],
            [514u] = [new QuestObjective("Skeleton Mage", "", 10, 1085u, 16u, -172.0f, 118.0f)],
            [515u] = [new QuestObjective("Jungle Minotaur", "", 100, 2010u, 14u, -23.0f, 74.0f)],
            [516u] = [new QuestObjective("Harpy", "", 100, 1106u, 15u, -209.0f, -154.0f)],
            [517u] = [new QuestObjective("Persian Archmage", "", 100, 3020u, 8u, -204.0f, 85.0f)],
            [520u] = [new QuestObjective("Dumb Wood Men", "", 10, 1027u, 0u, 186.0f, 8.0f)],
            [521u] = [new QuestObjective("Wooden Puppets", "", 12, 1021u, 0u, 139.0f, 52.0f)],
            [523u] = [new QuestObjective("Little Snakes", "", 12, 1012u, 0u, 188.0f, 111.0f)],
            [524u] = [new QuestObjective("Snakes", "", 15, 1015u, 0u, 162.0f, 198.0f)],
            [526u] = [new QuestObjective("Little Snakes", "", 15, 1012u, 0u, 117.0f, 104.0f)],
            [527u] = [new QuestObjective("Juno's Box", "", 15, 1023u, 0u, 56.0f, 133.0f)],
            [528u] = [new QuestObjective("Addiya the Destroyer", "", 1, 1492u, 0u, 39.0f, 180.0f), new QuestObjective("Fake Treasures", "Juno's Box", 8, 1023u, 0u, 71.0f, 191.0f)],
            [531u] = [new QuestObjective("Woodland Wolves", "", 20, 1431u, 4u, 202.0f, -200.0f)],
            [532u] = [new QuestObjective("Persian Spies", "", 20, 1432u, 4u, 65.0f, -45.0f)],
            [533u] = [new QuestObjective("Peninsula Bandits", "", 15, 1433u, 4u, 163.0f, -76.0f), new QuestObjective("Bloodthirsty Blademasters", "", 15, 1434u, 4u, 163.0f, -76.0f)],
            [535u] = [new QuestObjective("Garr the Fiend", "", 1, 1439u, 4u, -16.0f, 201.0f)],
            [536u] = [new QuestObjective("Scorpion Lord Alzet", "", 1, 1437u, 4u, -64.0f, -91.0f)],
            [537u] = [new QuestObjective("Flower Pixie", "", 1, 5275u, 4u, -36.0f, -208.0f), new QuestObjective("Minotaur", "", 1, 2010u, 4u, -36.0f, -208.0f)],
            [539u] = [new QuestObjective("Suburban Scorpions", "", 20, 1435u, 4u, 9.0f, -45.0f), new QuestObjective("Gold Tipped Scorpions", "", 20, 1436u, 4u, 9.0f, -45.0f)],
            [540u] = [new QuestObjective("Silver Mane Lions", "", 30, 1438u, 4u, 21.0f, 96.0f)],
            [541u] = [new QuestObjective("Sea Dragons", "", 25, 1440u, 4u, 120.0f, 105.0f), new QuestObjective("Young Sea Dragons", "", 25, 1441u, 4u, 120.0f, 105.0f)],
            [543u] = [new QuestObjective("Vicious Fawns", "", 30, 1442u, 4u, -13.0f, 39.0f)],
            [544u] = [new QuestObjective("Brown Dragons", "", 30, 1443u, 4u, -13.0f, 39.0f)],
            [545u] = [new QuestObjective("Fluttering Swords", "", 30, 1446u, 4u, -192.0f, 31.0f), new QuestObjective("Animated Axes", "", 30, 1445u, 4u, -110.0f, -56.0f), new QuestObjective("Wild Spears", "", 30, 1447u, 4u, -134.0f, -197.0f)],
            [546u] = [new QuestObjective("Divine Staff Selayan", "", 100, 1448u, 4u, -153.0f, -211.0f)],
            [547u] = [new QuestObjective("Gordon", "", 1, 1026u, 4u, -181.0f, 154.0f)],
            [549u] = [new QuestObjective("Plains Boas", "", 35, 1031u, 13u, 183.0f, -51.0f)],
            [550u] = [new QuestObjective("Huge Scorpions", "", 35, 1040u, 13u, 192.0f, -166.0f)],
            [552u] = [new QuestObjective("Toxic Scorpions", "", 40, 1042u, 13u, 26.0f, -127.0f)],
            [554u] = [new QuestObjective("Huge Scorpions", "", 40, 1040u, 13u, 110.0f, -131.0f)],
            [555u] = [new QuestObjective("Huge Spiders", "", 40, 1030u, 13u, 100.0f, 12.0f)],
            [556u] = [new QuestObjective("Irascible Evil Wizards", "", 40, 1044u, 13u, -136.0f, -52.0f)],
            [557u] = [new QuestObjective("Boas", "", 100, 1031u, 13u, 166.0f, 105.0f)],
            [558u] = [new QuestObjective("Toxic Scorpions", "", 100, 1042u, 13u, 99.0f, 139.0f)],
            [559u] = [new QuestObjective("spiders", "", 1, 1030u, 0u, 0.0f, 0.0f)],
            [560u] = [new QuestObjective("Athenian Captain Mills", "", 1, 1482u, 13u, -27.0f, 41.0f)],
            [561u] = [new QuestObjective("Evil Wizard", "", 1, 1044u, 13u, -78.0f, -162.0f)],
            [562u] = [new QuestObjective("Huge Skeleton", "", 1, 1043u, 13u, -40.0f, 160.0f)],
            [563u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 13u, -175.0f, 68.0f)],
            [564u] = [new QuestObjective("Sate Lord Kross as well as 60 Dark Wizards", "", 1, 1045u, 13u, -143.0f, 161.0f)],
            [566u] = [new QuestObjective("Athenian Frontline Soldier", "", 10, 1503u, 68u, -7.0f, -11.0f)],
            [571u] = [new QuestObjective("Athenian General", "", 1, 1500u, 68u, -127.0f, 150.0f)],
            [574u] = [new QuestObjective("Theban Spearmen", "", 200, 1509u, 9u, 71.0f, -23.0f)],
            [576u] = [new QuestObjective("Mycenaean Maulers", "", 200, 1530u, 9u, -52.0f, 41.0f)],
            [578u] = [new QuestObjective("Mycenaean Swordsmen", "", 1, 1531u, 9u, -86.0f, 177.0f), new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -30.0f, 198.0f)],
            [582u] = [new QuestObjective("Ravenous Deers", "", 200, 1533u, 9u, 58.0f, 174.0f)],
            [584u] = [new QuestObjective("Centaur Bandits", "", 200, 1534u, 9u, 158.0f, 92.0f)],
            [586u] = [new QuestObjective("Icy Basilisks", "", 200, 1515u, 9u, 97.0f, 41.0f)],
            [587u] = [new QuestObjective("Vagrant White Bulls", "", 200, 1536u, 9u, 184.0f, -11.0f)],
            [589u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f), new QuestObjective("Amazon Raiders", "", 1, 1535u, 9u, 97.0f, 41.0f)],
            [591u] = [new QuestObjective("Vagrant Brown Bulls", "", 200, 1537u, 9u, 174.0f, -159.0f)],
            [593u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f), new QuestObjective("Vagrant Brown Bulls", "", 1, 1537u, 9u, 174.0f, -159.0f)],
            [597u] = [new QuestObjective("Undead Raiders", "", 200, 1539u, 9u, -90.0f, -32.0f)],
            [601u] = [new QuestObjective("Undead Halberdier", "", 200, 1540u, 9u, -65.0f, -124.0f)],
            [604u] = [new QuestObjective("Death Mages", "", 200, 1070u, 9u, 48.0f, -114.0f)],
            [605u] = [new QuestObjective("Immortal Nolsan", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [610u] = [new QuestObjective("Immortal Nolsan", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [614u] = [new QuestObjective("Revived Khazras", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [615u] = [new QuestObjective("Revived Khazra", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [617u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [618u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [620u] = [new QuestObjective("Golden Scorpion Sukur", "", 1, 1544u, 9u, -190.0f, -195.0f)],
            [622u] = [new QuestObjective("Mycenaean Female Mages", "", 200, 1545u, 9u, -155.0f, 63.0f)],
            [623u] = [new QuestObjective("Mycenaean Royal Sorcerer!", "", 1, 1546u, 9u, -188.0f, 67.0f)],
            [625u] = [new QuestObjective("Scorpion Lord's Servants", "", 200, 1547u, 9u, -163.0f, -82.0f)],
            [626u] = [new QuestObjective("Scorpion Lord Selket!", "", 1, 1548u, 9u, -183.0f, -93.0f)],
            [627u] = [new QuestObjective("Mycenaean Spearmen", "", 100, 1529u, 9u, 71.0f, -23.0f)],
            [628u] = [new QuestObjective("Mycenaean Maulers", "", 100, 1530u, 9u, -52.0f, 41.0f)],
            [629u] = [new QuestObjective("Mycenaean Swordsmen", "", 100, 1531u, 9u, -86.0f, 177.0f)],
            [630u] = [new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -33.0f, 195.0f)],
            [631u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f)],
            [632u] = [new QuestObjective("Amazon Raiders", "", 100, 1535u, 9u, 97.0f, 41.0f)],
            [633u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f)],
            [635u] = [new QuestObjective("Undead Halberdiers", "", 100, 1540u, 9u, -65.0f, -124.0f)],
            [636u] = [new QuestObjective("Death Mages", "", 100, 1070u, 9u, 48.0f, -114.0f)],
            [637u] = [new QuestObjective("Undead Dark Mages", "", 100, 1541u, 9u, 48.0f, -114.0f)],
            [638u] = [new QuestObjective("Revived Khazras", "", 100, 1538u, 9u, -166.0f, 160.0f)],
            [639u] = [new QuestObjective("Lurking Mountain Scorpions", "", 100, 1543u, 9u, -109.0f, -158.0f)],
            [640u] = [new QuestObjective("Mycenaean Female Mages", "", 1, 1545u, 9u, -155.0f, 63.0f)],
            [641u] = [new QuestObjective("Scorpion Lord's Servants", "", 100, 1547u, 9u, -163.0f, -82.0f)],
            [642u] = [new QuestObjective("Undead Raiders", "", 300, 1539u, 9u, -90.0f, -32.0f)],
            [643u] = [new QuestObjective("Mycenaean Female Mages", "", 300, 1545u, 9u, -155.0f, 63.0f)],
            [644u] = [new QuestObjective("Scorpion Lord's Servants", "", 300, 1547u, 9u, -163.0f, -82.0f)],
            [645u] = [new QuestObjective("Gela Hunter", "", 100, 5167u, 32u, -82.0f, 155.0f)],
            [646u] = [new QuestObjective("Skeleton Captain Ixion", "", 200, 5292u, 32u, -169.0f, 160.0f)],
            [647u] = [new QuestObjective("Alpha Demon", "", 1, 1549u, 207u, 168.0f, -145.0f)],
            [648u] = [new QuestObjective("Undead Raider", "", 1000, 1539u, 9u, -90.0f, -32.0f)],
            [649u] = [new QuestObjective("Undead Halberdier", "", 5000, 1540u, 9u, -109.0f, -158.0f)],
            [650u] = [new QuestObjective("Nemean Lion", "", 1, 1550u, 210u, 121.0f, -124.0f)],
            [651u] = [new QuestObjective("Centaur", "", 500, 3007u, 9u, 158.0f, 92.0f)],
            [652u] = [new QuestObjective("Ravenous Deer", "", 50, 1533u, 9u, 58.0f, 174.0f)],
            [653u] = [new QuestObjective("guardian", "", 1, 8103u, 6u, 179.0f, -40.0f)],
            [654u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, -157.0f, 168.0f)],
            [655u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, 129.0f, -155.0f)],
            [1070u] = [new QuestObjective("Wild Boar", "", 100, 1051u, 3u, 41.0f, -58.0f)],
            [1080u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 3u, -129.0f, 45.0f)],
            [1083u] = [new QuestObjective("Death Mages", "", 1, 1070u, 18u, 1.0f, 1.0f)],
            [1087u] = [new QuestObjective("evil Mobs", "", 1, 1071u, 18u, 1.0f, 1.0f)],
            [1093u] = [new QuestObjective("Crocodile Selou", "", 100, 1072u, 18u, -161.0f, 56.0f)],
            [1095u] = [new QuestObjective("Skeleton Warrior", "", 100, 1074u, 18u, 71.0f, -55.0f)],
            [1097u] = [new QuestObjective("Skeleton Warlock", "", 100, 1075u, 18u, 154.0f, -41.0f)],
            [1100u] = [new QuestObjective("Illyria Brigands", "", 1, 1091u, 19u, 0.0f, -82.0f)],
            [1104u] = [new QuestObjective("Skeleton Warriors along the Megara Coast", "", 1, 1020u, 18u, 71.0f, -55.0f)],
            [1105u] = [new QuestObjective("Illyria Brigand", "", 100, 1091u, 19u, 0.0f, -82.0f)],
            [1106u] = [new QuestObjective("Scholar Kal", "", 100, 1094u, 19u, 102.0f, 66.0f)],
            [1110u] = [new QuestObjective("several Dark Wizards", "", 1, 1045u, 3u, -129.0f, 45.0f)],
            [1112u] = [new QuestObjective("Pallas Pit Viper", "", 10, 1073u, 18u, 19.0f, 2.0f)],
            [1118u] = [new QuestObjective("Boar King Tomas", "", 1, 1053u, 3u, 4.0f, -130.0f)],
            [1119u] = [new QuestObjective("Death Mages", "", 1, 1070u, 18u, -11.0f, 95.0f)],
            [1120u] = [new QuestObjective("Mob", "", 10, 1071u, 18u, 90.0f, 133.0f)],
            [1121u] = [new QuestObjective("Cyclops", "", 100, 1092u, 19u, 110.0f, -101.0f)],
            [1122u] = [new QuestObjective("Giant Alcyoneus", "", 1, 1093u, 19u, 195.0f, 10.0f)],
            [1143u] = [new QuestObjective("Skeleton Warlocks on the Megara Coast", "", 1, 1020u, 18u, 154.0f, -41.0f)],
            [1144u] = [new QuestObjective("Jaba Astrologist", "", 100, 1118u, 17u, 26.0f, 40.0f)],
            [1158u] = [new QuestObjective("Poisonous Spider", "", 100, 1050u, 3u, 135.0f, -81.0f)],
            [1159u] = [new QuestObjective("Witch", "", 100, 1052u, 3u, 18.0f, 3.0f)],
            [1160u] = [new QuestObjective("Dark Necromancer", "", 100, 1054u, 3u, -15.0f, 155.0f)],
            [1161u] = [new QuestObjective("Mob", "", 100, 1071u, 18u, 90.0f, 133.0f)],
            [1163u] = [new QuestObjective("Pallas Pit Viper", "", 100, 1073u, 18u, 19.0f, 2.0f)],
            [1164u] = [new QuestObjective("Skeleton Warrior", "", 100, 1074u, 18u, 71.0f, -55.0f)],
            [1165u] = [new QuestObjective("Strange Toad", "", 100, 1090u, 19u, -61.0f, -172.0f)],
            [1166u] = [new QuestObjective("Cyclops", "", 100, 1092u, 19u, 110.0f, -101.0f)],
            [1167u] = [new QuestObjective("Deigo Pirate", "", 100, 1101u, 15u, 5.0f, 42.0f)],
            [1168u] = [new QuestObjective("Persian Missionary", "", 100, 1104u, 15u, 157.0f, -20.0f)],
            [1172u] = [new QuestObjective("Little Weird Bird", "", 100, 1110u, 17u, -153.0f, 170.0f)],
            [1173u] = [new QuestObjective("Forest Magicians on the Isthmus of Corinth", "", 1, 1111u, 17u, 19.0f, 172.0f)],
            [1174u] = [new QuestObjective("Harpy's Underlings", "", 1, 1112u, 17u, 113.0f, 168.0f)],
            [1175u] = [new QuestObjective("Elf's Servant", "", 100, 1113u, 17u, -81.0f, 176.0f)],
            [1176u] = [new QuestObjective("Bronze Lions", "", 1, 1114u, 17u, -183.0f, 58.0f)],
            [1177u] = [new QuestObjective("Scary Turtle", "", 100, 1116u, 17u, 123.0f, 68.0f)],
            [1179u] = [new QuestObjective("Spartan  Patrolman", "", 100, 1087u, 15u, -34.0f, 99.0f)],
            [1180u] = [new QuestObjective("Spartan  Raidingman", "", 100, 1088u, 15u, 21.0f, 166.0f)],
            [1182u] = [new QuestObjective("Wandering Skeletons", "", 1, 1057u, 3u, -103.0f, -183.0f)],
            [1185u] = [new QuestObjective("Crispy Wood Men", "", 1, 1010u, 1u, 186.0f, -2.0f)],
            [1192u] = [new QuestObjective("Wasp", "", 15, 1014u, 1u, 164.0f, 170.0f)],
            [1200u] = [new QuestObjective("Witch", "", 100, 1052u, 3u, 18.0f, 3.0f)],
            [1201u] = [new QuestObjective("Poisonous Frog", "", 100, 1056u, 3u, 142.0f, -179.0f)],
            [1202u] = [new QuestObjective("Mob", "", 10, 1071u, 18u, 90.0f, 133.0f)],
            [1203u] = [new QuestObjective("Skeleton Warrior", "", 100, 1074u, 18u, 71.0f, -55.0f)],
            [1204u] = [new QuestObjective("Scary Turtle", "", 100, 1116u, 17u, 123.0f, 68.0f)],
            [1205u] = [new QuestObjective("Jaba Astrologist", "", 100, 1118u, 17u, -27.0f, 65.0f)],
            [1206u] = [new QuestObjective("Wind Elf", "", 100, 1096u, 19u, -170.0f, 57.0f)],
            [1210u] = [new QuestObjective("Sea Snake", "", 20, 1412u, 2u, 202.0f, -200.0f)],
            [1211u] = [new QuestObjective("One-eyed Ogre", "", 35, 1456u, 11u, -32.0f, -96.0f)],
            [1217u] = [new QuestObjective("Soul Holder Sameng", "", 1, 8061u, 18u, -65.0f, 100.0f)],
            [1221u] = [new QuestObjective("Beast Master", "", 1, 0u, 18u, 156.0f, -170.0f)],
            [1227u] = [new QuestObjective("Poisonous Frog", "", 100, 1056u, 3u, 142.0f, -179.0f)],
            [1228u] = [new QuestObjective("Crocodile Selou", "", 10, 1072u, 18u, -161.0f, 56.0f)],
            [1229u] = [new QuestObjective("Illyria Brigand", "", 100, 1091u, 19u, 0.0f, -82.0f)],
            [1230u] = [new QuestObjective("Wind Elf", "", 100, 1096u, 19u, -170.0f, 57.0f)],
            [1233u] = [new QuestObjective("Wild Boar", "", 100, 1051u, 3u, 41.0f, -58.0f)],
            [1235u] = [new QuestObjective("Poisonous Spiders", "", 1, 1050u, 3u, 135.0f, -81.0f)],
            [1236u] = [new QuestObjective("Poisonous Frogs", "", 1, 1056u, 3u, 142.0f, -179.0f)],
            [1238u] = [new QuestObjective("Salose", "", 1, 8042u, 3u, -150.0f, 192.0f)],
            [1239u] = [new QuestObjective("Wizard Plotau", "", 1, 8043u, 3u, -138.0f, -16.0f)],
            [1240u] = [new QuestObjective("Boar King Tomas with a group", "", 1, 1053u, 3u, 4.0f, -130.0f)],
            [1242u] = [new QuestObjective("Death Mages", "", 1, 1070u, 18u, -11.0f, 95.0f)],
            [1243u] = [new QuestObjective("Mobs", "", 1, 1071u, 18u, 90.0f, 133.0f)],
            [1244u] = [new QuestObjective("Pallas Pit Vipers", "", 1, 1073u, 18u, 19.0f, 2.0f)],
            [1245u] = [new QuestObjective("Skeleton Warriors", "", 1, 1074u, 18u, 71.0f, -55.0f)],
            [1246u] = [new QuestObjective("Skeleton Warlocks", "", 1, 1075u, 18u, 154.0f, -41.0f)],
            [1247u] = [new QuestObjective("Illyria Brigand", "", 100, 1091u, 19u, 0.0f, -82.0f)],
            [1249u] = [new QuestObjective("Persian Infiltrator", "", 10, 1413u, 2u, 80.0f, -158.0f)],
            [1250u] = [new QuestObjective("Bad Tempered Deer", "", 40, 1034u, 11u, 61.0f, -177.0f)],
            [1251u] = [new QuestObjective("Witch", "", 100, 1052u, 3u, 18.0f, 3.0f)],
            [1252u] = [new QuestObjective("Poisonous Frog", "", 100, 1056u, 3u, 142.0f, -179.0f)],
            [1253u] = [new QuestObjective("Death Mage", "", 10, 1070u, 18u, -11.0f, 95.0f)],
            [1254u] = [new QuestObjective("Crocodile Selou", "", 100, 1072u, 18u, -161.0f, 56.0f)],
            [1255u] = [new QuestObjective("Strange Toad", "", 100, 1090u, 19u, -61.0f, -172.0f)],
            [1256u] = [new QuestObjective("Cyclops", "", 100, 1092u, 19u, 110.0f, -101.0f)],
            [1257u] = [new QuestObjective("Scholar Kal", "", 100, 1094u, 19u, 102.0f, 66.0f)],
            [1258u] = [new QuestObjective("Wind Elf", "", 100, 1096u, 19u, -170.0f, 57.0f)],
            [1260u] = [new QuestObjective("Robber Lolo", "", 100, 1035u, 11u, 104.0f, -134.0f)],
            [1261u] = [new QuestObjective("Poisonous Frog", "", 100, 1056u, 3u, 142.0f, -179.0f)],
            [1262u] = [new QuestObjective("Crocodile Selou", "", 100, 1072u, 18u, -161.0f, 56.0f)],
            [1263u] = [new QuestObjective("Cyclops", "", 100, 1092u, 19u, 110.0f, -101.0f)],
            [1292u] = [new QuestObjective("Sicilian Elves", "", 100, 5160u, 32u, 136.0f, -110.0f)],
            [1293u] = [new QuestObjective("Numb Wolves", "", 100, 5161u, 32u, 62.0f, -115.0f)],
            [1294u] = [new QuestObjective("Ruthless Puppets", "", 100, 5162u, 32u, 74.0f, 32.0f)],
            [1295u] = [new QuestObjective("Blaze Vipers", "", 100, 5163u, 32u, 163.0f, 28.0f)],
            [1296u] = [new QuestObjective("Ice Wraiths", "", 100, 5165u, 32u, 206.0f, -21.0f)],
            [1297u] = [new QuestObjective("Gela Guards", "", 100, 5166u, 32u, 143.0f, 141.0f)],
            [1298u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, 102.0f, 138.0f)],
            [1300u] = [new QuestObjective("Wandering Skeletons", "", 50, 1057u, 3u, -103.0f, -183.0f)],
            [1306u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, 102.0f, 138.0f)],
            [1307u] = [new QuestObjective("Persian Scout", "", 100, 1095u, 19u, 23.0f, 81.0f), new QuestObjective("Persian Scout", "", 100, 3004u, 19u, 23.0f, 81.0f)],
            [1308u] = [new QuestObjective("Thorn Turtle", "", 100, 1097u, 19u, -92.0f, -94.0f)],
            [1309u] = [new QuestObjective("Scholar Kal", "", 100, 1094u, 19u, 102.0f, 66.0f)],
            [1310u] = [new QuestObjective("Wind Elf", "", 100, 1096u, 19u, -170.0f, 57.0f)],
            [1315u] = [new QuestObjective("Mutant Cruces", "", 100, 5290u, 32u, 48.0f, -160.0f)],
            [1316u] = [new QuestObjective("Wicked Alex", "", 100, 5291u, 32u, 62.0f, -28.0f)],
            [1317u] = [new QuestObjective("Skeleton Captain Ixion", "", 100, 5292u, 32u, 158.0f, 188.0f)],
            [1319u] = [new QuestObjective("Wind Elf", "", 100, 1096u, 19u, -170.0f, 57.0f)],
            [1320u] = [new QuestObjective("Huge Spider", "", 100, 1030u, 11u, 179.0f, 121.0f), new QuestObjective("Huge Spider", "", 100, 1039u, 11u, 179.0f, 121.0f)],
            [1321u] = [new QuestObjective("Queen Bee Guardian", "", 10, 1425u, 2u, -145.0f, 172.0f)],
            [1322u] = [new QuestObjective("Wandering Skeleton", "", 100, 1057u, 3u, -103.0f, -183.0f)],
            [1324u] = [new QuestObjective("Cyclops", "", 100, 1092u, 19u, 110.0f, -101.0f)],
            [1326u] = [new QuestObjective("Wild Boar", "", 10, 1051u, 3u, 4.0f, -130.0f)],
            [1330u] = [new QuestObjective("Dark Witches", "", 1, 3001u, 12u, 131.0f, -189.0f)],
            [1331u] = [new QuestObjective("Persian Scout", "", 100, 1095u, 12u, 158.0f, -58.0f), new QuestObjective("Persian Scout", "", 100, 3004u, 12u, 158.0f, -58.0f)],
            [1332u] = [new QuestObjective("those Venomous Icy Frogs around Parnitha Port", "", 1, 1037u, 12u, -30.0f, 104.0f)],
            [1333u] = [new QuestObjective("Dark Witch", "", 100, 3001u, 12u, 131.0f, -189.0f)],
            [1334u] = [new QuestObjective("Ghostly Warrior", "", 100, 3002u, 12u, 58.0f, -99.0f)],
            [1335u] = [new QuestObjective("Flaming Boas that infest Parnitha Port", "", 1, 1031u, 12u, -126.0f, -130.0f)],
            [1336u] = [new QuestObjective("Persian Clergies", "", 1, 3005u, 12u, 64.0f, 17.0f)],
            [1337u] = [new QuestObjective("Salt Water Crocodile", "", 100, 3006u, 12u, -22.0f, 0.0f)],
            [1338u] = [new QuestObjective("Centaur", "", 100, 3007u, 12u, 83.0f, 110.0f)],
            [1339u] = [new QuestObjective("Venomous Icy Frog", "", 100, 3009u, 12u, -30.0f, 104.0f)],
            [1340u] = [new QuestObjective("Venomsting Scorpion", "", 100, 3010u, 12u, -158.0f, 44.0f)],
            [1341u] = [new QuestObjective("Mudskippers", "", 1, 3011u, 12u, 137.0f, 176.0f)],
            [1343u] = [new QuestObjective("Dark Witches", "", 1, 3001u, 12u, 131.0f, -189.0f)],
            [1347u] = [new QuestObjective("Ghostly Warriors", "", 1, 3002u, 12u, 58.0f, -99.0f)],
            [1351u] = [new QuestObjective("Venomsting Scorpions", "", 1, 3010u, 12u, -158.0f, 44.0f)],
            [1353u] = [new QuestObjective("Rage Flamefrogs", "", 1, 3015u, 12u, -106.0f, 160.0f)],
            [1354u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, 87.0f, -111.0f)],
            [1355u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [1356u] = [new QuestObjective("Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [1357u] = [new QuestObjective("Rot Hide Cooers", "", 1, 3033u, 8u, 166.0f, -41.0f)],
            [1358u] = [new QuestObjective("White Cooers", "", 1, 3034u, 8u, 166.0f, -41.0f)],
            [1359u] = [new QuestObjective("Flaming Hound", "", 1, 3024u, 8u, 19.0f, -5.0f)],
            [1360u] = [new QuestObjective("Persian Huntresses", "", 1, 3025u, 8u, 18.0f, 71.0f)],
            [1361u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [1362u] = [new QuestObjective("Persian Whiterobe Mages", "", 1, 3032u, 8u, 1.0f, 1.0f)],
            [1363u] = [new QuestObjective("Persian Clergies", "", 1, 3005u, 8u, 102.0f, 168.0f)],
            [1364u] = [new QuestObjective("Persian Hammer Warriors", "", 1, 3027u, 8u, 182.0f, 127.0f)],
            [1365u] = [new QuestObjective("Persian Soldiers", "", 1, 3022u, 8u, -18.0f, 113.0f)],
            [1366u] = [new QuestObjective("Persian Bowyers", "", 1, 3023u, 8u, -14.0f, 148.0f)],
            [1367u] = [new QuestObjective("Persian Archmages", "", 1, 3020u, 8u, -118.0f, 57.0f)],
            [1368u] = [new QuestObjective("Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [1370u] = [new QuestObjective("Persian Whiterobe Mage", "", 100, 3032u, 8u, 72.0f, 107.0f)],
            [1374u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, 87.0f, -111.0f)],
            [1376u] = [new QuestObjective("Persian Captain", "", 1, 3038u, 8u, -70.0f, 165.0f)],
            [1380u] = [new QuestObjective("all the Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [1382u] = [new QuestObjective("Mardonius", "", 1, 3030u, 8u, -184.0f, 32.0f)],
            [1386u] = [new QuestObjective("Milier Guardsmen", "", 1, 1117u, 17u, 188.0f, -43.0f)],
            [1387u] = [new QuestObjective("Skeleton Mage of Argolis", "", 1, 1020u, 16u, -148.0f, 16.0f)],
            [1388u] = [new QuestObjective("Young RedDragons", "", 1, 1119u, 17u, -161.0f, -49.0f)],
            [1393u] = [new QuestObjective("Persian Mages", "", 1, 3036u, 8u, 68.0f, -149.0f)],
            [1394u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, 68.0f, -149.0f)],
            [1408u] = [new QuestObjective("Wizard", "", 10, 1062u, 3u, -138.0f, -16.0f)],
            [1409u] = [new QuestObjective("Wizard", "", 10, 1062u, 3u, -129.0f, 45.0f)],
            [1410u] = [new QuestObjective("Huge Spider", "", 50, 1030u, 11u, 85.0f, -63.0f), new QuestObjective("Huge Spider", "", 50, 1039u, 11u, 85.0f, -63.0f)],
            [1412u] = [new QuestObjective("Vicious Wolf", "", 50, 1032u, 11u, 90.0f, 124.0f)],
            [1413u] = [new QuestObjective("Dark Necromancer", "", 10, 1054u, 3u, -150.0f, 192.0f), new QuestObjective("Salose", "", 10, 8042u, 3u, -150.0f, 192.0f)],
            [1414u] = [new QuestObjective("Little Snake", "", 30, 1012u, 1u, 117.0f, 104.0f), new QuestObjective("Little Snake", "", 30, 1028u, 1u, 117.0f, 104.0f)],
            [1415u] = [new QuestObjective("Forest Magician", "", 30, 1111u, 17u, 19.0f, 172.0f)],
            [1416u] = [new QuestObjective("Boar King Tomas", "", 10, 1053u, 3u, 4.0f, -130.0f)],
            [1417u] = [new QuestObjective("Kelly the Venom Queen", "", 10, 1426u, 2u, -184.0f, 160.0f)],
            [1418u] = [new QuestObjective("Sea Snake", "", 10, 1412u, 2u, 202.0f, -200.0f)],
            [1419u] = [new QuestObjective("Wild Boar", "", 30, 1051u, 3u, 41.0f, -58.0f)],
            [1421u] = [new QuestObjective("Death Mage", "", 50, 1070u, 18u, -11.0f, 95.0f)],
            [1422u] = [new QuestObjective("Mob", "", 10, 1071u, 18u, 90.0f, 133.0f)],
            [1423u] = [new QuestObjective("Little Weird Bird", "", 30, 1110u, 17u, -153.0f, 170.0f)],
            [1424u] = [new QuestObjective("Pallas Pit Viper", "", 20, 1073u, 18u, 19.0f, 2.0f)],
            [1425u] = [new QuestObjective("Skeleton Warrior", "", 10, 1074u, 18u, 71.0f, -55.0f)],
            [1426u] = [new QuestObjective("Skeleton Warlock", "", 10, 1075u, 18u, 154.0f, -41.0f)],
            [1427u] = [new QuestObjective("Poisonous Frog", "", 50, 1056u, 3u, 142.0f, -179.0f)],
            [1428u] = [new QuestObjective("Witch", "", 30, 1052u, 3u, 18.0f, 3.0f)],
            [1429u] = [new QuestObjective("Young Flamescale Dragon", "", 40, 1427u, 2u, -109.0f, -92.0f)],
            [1430u] = [new QuestObjective("Little Deer", "", 20, 1011u, 1u, 188.0f, 111.0f)],
            [1431u] = [new QuestObjective("Little Bee", "", 10, 1013u, 1u, 186.0f, 8.0f)],
            [1432u] = [new QuestObjective("Skeleton Warlock", "", 50, 1075u, 18u, 154.0f, -41.0f)],
            [1434u] = [new QuestObjective("Harpy", "", 40, 1106u, 17u, 113.0f, 168.0f)],
            [1435u] = [new QuestObjective("Bad Tempered Deer", "", 30, 1034u, 11u, 140.0f, -40.0f)],
            [1436u] = [new QuestObjective("Robber Lolo", "", 10, 1035u, 11u, 179.0f, 121.0f)],
            [1438u] = [new QuestObjective("Wandering Skeleton", "", 40, 1057u, 3u, -103.0f, -183.0f)],
            [1439u] = [new QuestObjective("Strange Toad", "", 20, 1090u, 19u, -61.0f, -172.0f)],
            [1440u] = [new QuestObjective("Crocodile Selou", "", 50, 1072u, 18u, -161.0f, 56.0f)],
            [1441u] = [new QuestObjective("Great Mane Plains Lion", "", 10, 1416u, 2u, 9.0f, -45.0f)],
            [1442u] = [new QuestObjective("Plumed Harpy", "", 10, 1414u, 2u, 163.0f, -76.0f)],
            [1445u] = [new QuestObjective("One-eyed Ogre", "", 10, 1456u, 11u, -32.0f, -96.0f)],
            [1446u] = [new QuestObjective("Frog", "", 10, 1037u, 11u, 6.0f, 155.0f)],
            [1447u] = [new QuestObjective("Centauri Heathen", "", 1, 5060u, 29u, -160.0f, 142.0f)],
            [1457u] = [new QuestObjective("Persian Infiltrator", "", 500, 1413u, 2u, 80.0f, -158.0f)],
            [1458u] = [new QuestObjective("Bad Tempered Deer", "", 500, 1034u, 11u, 61.0f, -177.0f)],
            [1459u] = [new QuestObjective("Witch", "", 100, 1052u, 3u, 18.0f, 3.0f)],
            [1460u] = [new QuestObjective("Poisonous Frog", "", 500, 1056u, 3u, 142.0f, -179.0f)],
            [1461u] = [new QuestObjective("Death Mage", "", 10, 1070u, 18u, -11.0f, 95.0f)],
            [1462u] = [new QuestObjective("Crocodile Selou", "", 500, 1072u, 18u, -161.0f, 56.0f)],
            [1463u] = [new QuestObjective("Strange Toad", "", 100, 1090u, 19u, -61.0f, -172.0f)],
            [1464u] = [new QuestObjective("Cyclops", "", 500, 1092u, 19u, 110.0f, -101.0f)],
            [1465u] = [new QuestObjective("Scholar Kal", "", 500, 1094u, 19u, 102.0f, 66.0f)],
            [1466u] = [new QuestObjective("Wind Elf", "", 500, 1096u, 19u, -170.0f, 57.0f)],
            [1474u] = [new QuestObjective("White Cooer", "", 50, 3034u, 8u, 179.0f, -38.0f), new QuestObjective("Rot Hide Cooer", "", 50, 3033u, 8u, 179.0f, -38.0f)],
            [1509u] = [new QuestObjective("Death Mage", "", 10, 1070u, 18u, 1.0f, 1.0f)],
            [1511u] = [new QuestObjective("Persian Scout", "", 100, 1095u, 19u, 1.0f, 1.0f), new QuestObjective("Persian Scout", "", 100, 3004u, 19u, 1.0f, 1.0f)],
            [1512u] = [new QuestObjective("Persian Huntress", "", 100, 3025u, 8u, 1.0f, 1.0f)],
            [1513u] = [new QuestObjective("Dark Wizard", "", 100, 1045u, 3u, -190.0f, -64.0f), new QuestObjective("Dark Wizard", "", 100, 1055u, 3u, -190.0f, -64.0f)],
            [1514u] = [new QuestObjective("Skeleton Warlock", "", 10, 1075u, 18u, 182.0f, -32.0f)],
            [1515u] = [new QuestObjective("Centaur", "", 100, 3007u, 12u, 87.0f, 146.0f)],
            [1516u] = [new QuestObjective("Wind Elf", "", 100, 1096u, 19u, -67.0f, 58.0f)],
            [1517u] = [new QuestObjective("Persian Archmage", "", 100, 3020u, 8u, -204.0f, 85.0f)],
            [1520u] = [new QuestObjective("Crispy Wood Man", "", 10, 1010u, 1u, 186.0f, 8.0f)],
            [1521u] = [new QuestObjective("Little Deer", "", 12, 1011u, 1u, 139.0f, 52.0f)],
            [1523u] = [new QuestObjective("Little Bees", "", 12, 1013u, 1u, 188.0f, 111.0f)],
            [1524u] = [new QuestObjective("Wasps", "", 15, 1014u, 1u, 162.0f, 198.0f)],
            [1526u] = [new QuestObjective("Little Bees", "", 15, 1013u, 1u, 117.0f, 104.0f)],
            [1527u] = [new QuestObjective("Little Snakes", "", 15, 1012u, 1u, 54.0f, 134.0f)],
            [1528u] = [new QuestObjective("Wilemet the Controller", "", 1, 1411u, 1u, 39.0f, 180.0f)],
            [1531u] = [new QuestObjective("Sea Snakes", "", 20, 1412u, 2u, 214.0f, -192.0f)],
            [1532u] = [new QuestObjective("Persian Infiltrators", "", 20, 1413u, 2u, 65.0f, -45.0f)],
            [1533u] = [new QuestObjective("Plumed Harpies", "", 15, 1414u, 2u, 163.0f, -76.0f), new QuestObjective("Frenzied Harpies", "", 15, 1415u, 2u, 163.0f, -76.0f)],
            [1535u] = [new QuestObjective("Snake Queen Johnna", "", 1, 1420u, 2u, -16.0f, 201.0f)],
            [1536u] = [new QuestObjective("Lion Lord Wilyeen", "", 1, 1418u, 2u, -64.0f, -91.0f)],
            [1537u] = [new QuestObjective("Flower Pixie", "", 1, 5275u, 2u, -36.0f, -208.0f), new QuestObjective("Minotaur", "", 1, 2010u, 2u, -36.0f, -208.0f)],
            [1539u] = [new QuestObjective("Great Mane Plains Lions", "", 20, 1416u, 2u, 9.0f, -45.0f), new QuestObjective("Silver Mane Plains Lions", "", 20, 1417u, 2u, 9.0f, -45.0f)],
            [1540u] = [new QuestObjective("Demonic Black Snakes", "", 30, 1419u, 2u, 21.0f, 96.0f)],
            [1541u] = [new QuestObjective("Suburban Sea Turtles", "", 25, 1421u, 2u, 120.0f, 105.0f), new QuestObjective("Sleepy Saltwater Turtles", "", 25, 1422u, 2u, 120.0f, 105.0f)],
            [1543u] = [new QuestObjective("Farm Wasps", "", 30, 1423u, 2u, -13.0f, 39.0f)],
            [1544u] = [new QuestObjective("Woodland Drones", "", 30, 1424u, 2u, -13.0f, 39.0f)],
            [1545u] = [new QuestObjective("Young Firemane Dragons", "", 30, 1428u, 2u, -192.0f, 31.0f), new QuestObjective("Young Flamescale Dragons", "", 30, 1427u, 2u, -109.0f, -92.0f), new QuestObjective("Young Jade Dragons", "", 30, 1429u, 2u, -134.0f, -197.0f)],
            [1546u] = [new QuestObjective("Young Armored Dragon", "", 100, 1430u, 2u, -153.0f, -211.0f)],
            [1547u] = [new QuestObjective("Kelly the Venom Queen", "", 1, 1426u, 2u, -184.0f, 160.0f)],
            [1549u] = [new QuestObjective("Boas", "", 35, 1031u, 11u, 179.0f, 121.0f)],
            [1550u] = [new QuestObjective("Vicious Wolves", "", 35, 1032u, 11u, 90.0f, 124.0f)],
            [1552u] = [new QuestObjective("Robber Lolos", "", 40, 1035u, 11u, 110.0f, -128.0f)],
            [1553u] = [new QuestObjective("[Elite]Thief Lord Alwa", "", 40, 1453u, 11u, 134.0f, -145.0f)],
            [1554u] = [new QuestObjective("Bad Tempered Deer", "", 40, 1034u, 11u, 140.0f, -40.0f)],
            [1555u] = [new QuestObjective("Huge Lions", "", 40, 1033u, 11u, -32.0f, -96.0f)],
            [1556u] = [new QuestObjective("Crocodiles", "", 40, 1038u, 11u, -99.0f, -163.0f)],
            [1557u] = [new QuestObjective("Angry Deer", "", 100, 0u, 11u, 85.0f, -63.0f)],
            [1558u] = [new QuestObjective("Frogs", "", 100, 1037u, 11u, -14.0f, -171.0f)],
            [1559u] = [new QuestObjective("Lions", "", 1, 1025u, 0u, 0.0f, 0.0f)],
            [1560u] = [new QuestObjective("Spartan Captain Adron", "", 1, 1466u, 11u, 14.0f, 10.0f)],
            [1561u] = [new QuestObjective("Angry Deer", "", 60, 0u, 11u, -115.0f, -66.0f)],
            [1562u] = [new QuestObjective("Crocodiles", "", 60, 1038u, 11u, -156.0f, -109.0f)],
            [1563u] = [new QuestObjective("Vicious Wolves", "", 60, 1032u, 11u, 6.0f, 155.0f)],
            [1564u] = [new QuestObjective("Skeletal Lord Darnas as well as 60 Huge Lion", "", 1, 1025u, 11u, -184.0f, 182.0f)],
            [1566u] = [new QuestObjective("Spartan Frontline Soldier", "", 10, 1502u, 68u, -7.0f, -11.0f)],
            [1571u] = [new QuestObjective("Spartan General", "", 1, 1501u, 68u, 119.0f, -136.0f)],
            [1574u] = [new QuestObjective("Mycenaean Spearmen", "", 200, 1529u, 9u, 71.0f, -23.0f)],
            [1576u] = [new QuestObjective("Mycenaean Maulers", "", 200, 1530u, 9u, -52.0f, 41.0f)],
            [1578u] = [new QuestObjective("Mycenaean Swordsmen", "", 1, 1531u, 9u, -86.0f, 177.0f), new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -30.0f, 198.0f)],
            [1582u] = [new QuestObjective("Ravenous Deer", "", 200, 1533u, 9u, 58.0f, 174.0f)],
            [1584u] = [new QuestObjective("Centaur Bandits", "", 200, 1534u, 9u, 158.0f, 92.0f)],
            [1586u] = [new QuestObjective("Amazon Raiders", "", 200, 1535u, 9u, 97.0f, 41.0f)],
            [1587u] = [new QuestObjective("Vagrant White Bulls", "", 200, 1536u, 9u, 184.0f, -11.0f)],
            [1589u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f), new QuestObjective("Amazon Raiders", "", 1, 1535u, 9u, 97.0f, 41.0f)],
            [1591u] = [new QuestObjective("Vagrant Brown Bulls", "", 200, 1537u, 9u, 174.0f, -159.0f)],
            [1593u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f), new QuestObjective("Vagrant Brown Bulls", "", 1, 1537u, 9u, 174.0f, -159.0f)],
            [1597u] = [new QuestObjective("Undead Raiders", "", 200, 1539u, 9u, -90.0f, -32.0f)],
            [1601u] = [new QuestObjective("Undead Halberdiers", "", 200, 1540u, 9u, -65.0f, -124.0f)],
            [1604u] = [new QuestObjective("Undead Dark Mages", "", 200, 1541u, 9u, 48.0f, -114.0f)],
            [1605u] = [new QuestObjective("Immortal Nolsan!", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [1610u] = [new QuestObjective("Immortal Nolsan", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [1614u] = [new QuestObjective("Revived Khazra", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [1615u] = [new QuestObjective("Revived Khazra", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [1617u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [1618u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [1620u] = [new QuestObjective("Golden Scorpion Sukur", "", 1, 1544u, 9u, -190.0f, -195.0f)],
            [1622u] = [new QuestObjective("Mycenaean Female Mages", "", 200, 1545u, 9u, -155.0f, 63.0f)],
            [1623u] = [new QuestObjective("Mycenaean Royal Sorcerer", "", 1, 1546u, 9u, -188.0f, 67.0f)],
            [1625u] = [new QuestObjective("Scorpion Lord's Servants", "", 200, 1547u, 9u, -163.0f, -82.0f)],
            [1626u] = [new QuestObjective("Scorpion Lord Selket!", "", 1, 1548u, 9u, -183.0f, -93.0f)],
            [1627u] = [new QuestObjective("Mycenaean Spearmen", "", 100, 1529u, 9u, 71.0f, -23.0f)],
            [1628u] = [new QuestObjective("Mycenaean Maulers", "", 100, 1530u, 9u, -52.0f, 41.0f)],
            [1629u] = [new QuestObjective("Mycenaean Swordsmen", "", 100, 1531u, 9u, -86.0f, 177.0f)],
            [1630u] = [new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -33.0f, 195.0f)],
            [1631u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f)],
            [1632u] = [new QuestObjective("Amazon Raiders", "", 100, 1535u, 9u, 97.0f, 41.0f)],
            [1633u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f)],
            [1635u] = [new QuestObjective("Undead Halberdiers", "", 100, 1540u, 9u, -65.0f, -124.0f)],
            [1636u] = [new QuestObjective("Undead Dark Mages", "", 100, 1541u, 9u, 48.0f, -114.0f)],
            [1637u] = [new QuestObjective("Undead Dark Mages", "", 100, 1541u, 9u, 48.0f, -114.0f)],
            [1638u] = [new QuestObjective("Revived Khazras", "", 100, 1538u, 9u, -166.0f, 160.0f)],
            [1639u] = [new QuestObjective("Lurking Mountain Scorpions", "", 100, 1543u, 9u, -109.0f, -158.0f)],
            [1640u] = [new QuestObjective("Mycenaean Female Mages", "", 100, 1545u, 9u, -155.0f, 63.0f)],
            [1641u] = [new QuestObjective("Scorpion Lord's Servants", "", 100, 1547u, 9u, -163.0f, -82.0f)],
            [1642u] = [new QuestObjective("Undead Raiders", "", 300, 1539u, 9u, -90.0f, -32.0f)],
            [1643u] = [new QuestObjective("Mycenaean Female Mages", "", 300, 1545u, 9u, -155.0f, 63.0f)],
            [1644u] = [new QuestObjective("Scorpion Lord's Servants", "", 300, 1547u, 9u, -163.0f, -82.0f)],
            [1645u] = [new QuestObjective("Gela Hunter", "", 100, 5167u, 32u, 102.0f, 138.0f)],
            [1646u] = [new QuestObjective("Skeleton Captain Ixion", "", 200, 5292u, 32u, 158.0f, 188.0f)],
            [1647u] = [new QuestObjective("Alpha Demon", "", 1, 1549u, 207u, 168.0f, -145.0f)],
            [1648u] = [new QuestObjective("Undead Dark Mage", "", 1000, 1541u, 9u, -166.0f, 160.0f)],
            [1649u] = [new QuestObjective("Vagrant Brown Bull", "", 5000, 1537u, 9u, 174.0f, -159.0f)],
            [1650u] = [new QuestObjective("Nemean Lion", "", 1, 1550u, 210u, 121.0f, -124.0f)],
            [1651u] = [new QuestObjective("Centaur", "", 500, 3007u, 9u, 158.0f, 92.0f)],
            [1652u] = [new QuestObjective("Ravenous Deer", "", 500, 1533u, 9u, 58.0f, 174.0f)],
            [1653u] = [new QuestObjective("guardian", "", 1, 8103u, 6u, 179.0f, -40.0f)],
            [1654u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, -157.0f, 168.0f)],
            [1655u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, 129.0f, -155.0f)],
        };

    /// <summary>The objectives of a quest, empty when it has none.</summary>
    public static IReadOnlyList<QuestObjective> For(uint questId) =>
        ByQuestId.TryGetValue(questId, out var objectives)
            ? objectives
            : [];

    /// <summary>Reads one objective's counter out of the packed progress.</summary>
    public static int Counter(long progress, int slot) =>
        (int)((progress >> (slot * CounterBits)) & CounterMaximum);

    /// <summary>Writes one objective's counter back into the progress.</summary>
    public static long WithCounter(long progress, int slot, int value)
    {
        var clamped = Math.Clamp(value, 0, CounterMaximum);
        var shift = slot * CounterBits;
        return (progress & ~((long)ushort.MaxValue << shift)) |
            ((long)clamped << shift);
    }

    /// <summary>True when every objective has been satisfied.</summary>
    public static bool IsSatisfied(
        IReadOnlyList<QuestObjective> objectives,
        long progress)
    {
        for (var slot = 0; slot < objectives.Count; slot++)
        {
            if (Counter(progress, slot) < objectives[slot].Required)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>True when a killed monster satisfies this objective.</summary>
    public static bool Matches(
        QuestObjective objective,
        uint mapId,
        string? monsterName,
        float x,
        float z)
    {
        if (objective.MapId != mapId)
        {
            return false;
        }

        if (Needle(NameOf(objective)) is { Length: > 0 } &&
            Needle(monsterName) is { Length: > 0 })
        {
            // The quest text is sloppy about plurals - "Woodland
            // Wolves" for the client's "Woodland Wolf" - so the two
            // names are compared through every shape the plural can
            // stand for, not just the folded text.
            return SameName(NameOf(objective), monsterName);
        }

        var dx = objective.X - x;
        var dz = objective.Z - z;
        return (dx * dx) + (dz * dz) <= MatchRadius * MatchRadius;
    }

    /// <summary>
    /// The name a kill has to carry to credit this objective: the client's
    /// own name for the target when the quest text calls it something else.
    /// </summary>
    public static string NameOf(QuestObjective objective) =>
        string.IsNullOrWhiteSpace(objective.Match)
            ? objective.Target
            : objective.Match;

    /// <summary>
    /// Reduces a display name to letters and digits so plurals and colour
    /// markup do not stop a match.
    /// </summary>
    /// <remarks>
    /// The quest text says "Kill 10 Dumb Wood Men" while the monster is
    /// called "Dumb Wood Man", and 521 says "Wooden Puppets" for the
    /// monster "Wooden Puppet", so a trailing plural is dropped and the
    /// irregular "men" is folded onto "man".
    /// </remarks>
    internal static string Needle(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        var plain = ColorMarkup().Replace(value, string.Empty);
        var builder = new StringBuilder(plain.Length);
        var separator = false;
        foreach (var character in plain)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(char.ToLowerInvariant(character));
                separator = true;
            }
            else if (separator)
            {
                builder.Append(' ');
                separator = false;
            }
        }

        var words = new List<string>();
        foreach (var word in builder.ToString().Split(
                     ' ', StringSplitOptions.RemoveEmptyEntries))
        {
            words.Add(word switch
            {
                "men" => "man",
                _ when word.Length > 3 && word.EndsWith('s') =>
                    word[..^1],
                _ => word
            });
        }

        return string.Join(' ', words);
    }

    [GeneratedRegex(
        @"\|c[0-9a-fA-F]{8}",
        RegexOptions.CultureInvariant)]
    private static partial Regex ColorMarkup();
}
