// Generated by tools/gen_quest_objective_frames.py; do not edit
// by hand. The frames are the reference server's own packets,
// captured while a kill quest was accepted and worked on.

using System.Buffers.Binary;
using Godswar.Server.Domain.World.Content;
using Godswar.Server.Protocol;

namespace Godswar.Server.Packets;

internal static partial class PacketBuilder
{
    /// <summary>S2C 10081, the reference server's quest detail frame (packet 84550).</summary>
    private static readonly byte[] Objective10081Bytes = Convert.FromHexString(
        "68016127BE130000080200000000000008000000000000000000000003040000000000000000000000000000" +
        "0A00000000000000000000000000000000000000000000000000000034080000FFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFFFFFFFFFF030101010000000000000000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0101000100000000" +
        "00000000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFF" +
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF010100010000000000000000000000000000000000000000" +
        "000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFF01010001000000000000000000000000000000000000000000000000000000000000000000000000" +
        "0000000000000000");

    /// <summary>S2C 10082, the reference server's accepted quest frame (packet 84573).</summary>
    private static readonly byte[] Objective10082Bytes = Convert.FromHexString(
        "88026227BE130000BE1300000802000000000000080000000000000000000000030400000000000000000000" +
        "000000000A000000000000000000000000000000000000000000000034080000FFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFFFFFFFFFF030101010000000000000000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0101000100000000" +
        "00000000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFF" +
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF010100010000000000000000000000000000000000000000" +
        "000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFF01010001000000000000000000000000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF010100000000000000000000" +
        "00000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF00000000FFFFFFFF" +
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF01010000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" +
        "01010000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFF" +
        "FFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF01010000000000000000000000000000" +
        "000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF");

    /// <summary>S2C 10087, the reference server's progress step frame (packet 84740).</summary>
    private static readonly byte[] Objective10087Bytes = Convert.FromHexString(
        "1400672708020000BE1300000100000003040000");

    /// <summary>S2C 10081, the detail of a kill quest.</summary>
    /// <remarks>
    /// Payload +0 npc, +4 quest, +24 target monster id and +40 how
    /// many are wanted.
    /// <para>
    /// The target area is the same parallel u16 arrays as the accept answer and
    /// the follow-up detail, four bytes earlier again: slot <c>i</c> holds one
    /// monster at <c>+28 + 2i</c> and one count at <c>+44 + 2i</c>, and the item
    /// half of the quest's objectives sits beside them at <c>+20</c>/<c>+36</c>.
    /// The reference server's own detail for the two-target quest 1541 carries
    /// 1421 and 1422 in those two slots, so every target the quest names is
    /// written - writing the target as a single <c>u32</c>, which is what this
    /// builder used to do, is what left a multi-target quest's window with one
    /// objective.
    /// </para>
    /// </remarks>
    public static byte[] QuestObjectiveDetail(
        uint npcId,
        uint questId,
        uint monsterId,
        int required)
    {
        var packet = (byte[])Objective10081Bytes.Clone();
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(4, 4), npcId);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(8, 4), questId);
        // The content table is the same source the accept answer uses, so the
        // detail cannot disagree with it. A quest it does not carry keeps the
        // caller's own single target.
        var content = Godswar.Server.Game.GameClientHandler.DisplayQuestObjectives(questId);
        IReadOnlyList<QuestObjective> objectives = content.Count > 0
            ? content
            :
            [
                new QuestObjective(
                    string.Empty,
                    string.Empty,
                    required,
                    monsterId,
                    0u,
                    0f,
                    0f)
            ];
        WriteObjectiveSlots(
            packet,
            QuestNextDetailMonsterOffset,
            QuestNextDetailRequiredOffset,
            objectives);
        WriteCollectObjective(
            packet,
            QuestNextDetailItemIdOffset,
            QuestNextDetailItemCountOffset,
            questId);
        var hasObjectives = content.Count > 0 ||
            StarterQuestCollectObjectives.TryGet(questId, out _);
        BinaryPrimitives.WriteInt32LittleEndian(
            packet.AsSpan(QuestNextDetailKindOffset, 4),
            hasObjectives ? QuestWithObjectivesKind : 4);
        return packet;
    }

    /// <summary>S2C 10087, one step of quest progress.</summary>
    /// <remarks>
    /// Payload +0 quest, +4 npc, +8 the step (always 1 in the
    /// capture - one kill) and +12 the target monster id.
    /// </remarks>
    public static byte[] QuestObjectiveProgress(
        uint questId,
        uint npcId,
        uint monsterId,
        int step = 1)
    {
        var packet = (byte[])Objective10087Bytes.Clone();
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(4, 4), questId);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(8, 4), npcId);
        BinaryPrimitives.WriteInt32LittleEndian(
            packet.AsSpan(12, 4), step);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(16, 4), monsterId);
        return packet;
    }
}
