"""Audit active client text and generate verified exploration/PvP requirements.

Missing counts, item sources, and cross-language discrepancies are reported,
never silently converted into completed dialogue quests.
"""
from pathlib import Path
import collections
import hashlib
import json
import re
import sys

import gen_sparta_quest_chain as chain
import gen_quest_objectives as kills

ROOT = Path(__file__).resolve().parents[1]
CLIENT = Path(r"D:\Godswar Origin")
OUT = ROOT / "artifacts/quest-runtime-content-20261007"


def blocks(path):
    text = kills.read_text(str(path))
    return {key: re.sub(r"\s+", " ", value).strip()
            for key, value in re.findall(r"(\w+)\s*\{(.*?)\}", text, re.S)}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = chain.quest_rows()
    selected, excluded = chain.select(rows, chain.published_npcs())
    ids = sorted(q[0] for group in selected.values() for q in group)
    scrolls = collections.defaultdict(list)
    item_xml = CLIENT / "Localization/zh_cn/Settings/Sys/ItemBaseAttribute.xml"
    for tag in re.findall(r"<[^>]+>", item_xml.read_text(encoding="utf-8-sig")):
        attrs = dict(re.findall(r'(\w+)\s*=\s*"([^"]*)"', tag))
        if attrs.get("Quest", "").isdigit() and attrs.get("ID", "").isdigit():
            scrolls[int(attrs["Quest"])].append(int(attrs["ID"]))
    requirements = []
    audit = []
    for qid in ids:
        row = rows[qid]
        cn = blocks(CLIENT / f"Localization/zh_cn/Text/Quest/{qid}.dat")
        en = blocks(CLIENT / f"Localization/en_us/Text/Quest/{qid}.dat")
        plain = re.sub(r"\|c[0-9a-fA-F]{8}", "", cn.get("Objectives", ""))
        maps = [int(x) for x in row.get("ExplorerMapID", "").split(",") if x]
        coords = [float(x) for x in row.get("ExplorerMapPosition", "").split(",") if x]
        points = []
        if maps:
            if len(coords) != len(maps) * 2 or len(maps) > 4:
                raise ValueError(f"Invalid exploration coordinates for {qid}")
            points = [dict(map=map_id, x=coords[i * 2], z=coords[i * 2 + 1])
                      for i, map_id in enumerate(maps)]
        pvp = re.search(r"(?:击杀|消灭|杀死).*?(\d+)级以上玩家", plain)
        pvp_count = 0
        if pvp:
            count = re.search(r"(?:击杀|消灭|杀死)\s*(\d+|一)\s*名", plain)
            if not count:
                raise ValueError(f"Missing explicit PvP count for {qid}: {plain}")
            pvp_count = 1 if count[1] == "一" else int(count[1])
        handin = re.search(r"需要\s*(\d+)\s*级才能交付", plain)
        req = dict(id=qid, exploration=points, playerKills=pvp_count,
                   playerMinimumLevel=int(pvp[1]) if pvp else 0,
                   playerMap=int(row["CreatureMapID"]) if pvp else -1,
                   handInMinimumLevel=int(handin[1]) if handin else 0)
        if points or pvp or handin:
            requirements.append(req)
        types = []
        if row["GiverName"] == "QuestScroll": types.append("scroll")
        if points: types.append("exploration")
        if pvp: types.append("player-kill")
        elif row.get("CreatureMapID"): types.append("monster")
        if row.get("ItemMapID"): types.append("collect")
        if not any(t in types for t in ("monster", "collect", "exploration", "player-kill")):
            types.append("dialogue-or-feature")
        audit.append(dict(id=qid, types=types, chinese=cn, english=en,
                          xml=row, requirements=req, scrollItems=scrolls[qid],
                          chineseTextHash=hashlib.sha256(json.dumps(cn, ensure_ascii=False,
                              sort_keys=True).encode()).hexdigest()))
    (OUT / "all-quest-text-and-rules.json").write_text(
        json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = ["// Generated by tools/audit_quest_runtime_content.py; verified client fields only.",
             "namespace Godswar.Server.Domain.World.Content;", "",
             "internal static class QuestAdditionalRequirements", "{",
             "    internal readonly record struct ExplorePoint(int Map, float X, float Z);",
             "    internal sealed record Requirement(ExplorePoint[] Exploration, int PlayerKills,",
             "        int PlayerMinimumLevel, int PlayerMap, int HandInMinimumLevel);",
             "    internal static readonly IReadOnlyDictionary<uint, Requirement> ByQuestId =",
             "        new Dictionary<uint, Requirement>", "        {"]
    for r in requirements:
        pts = ", ".join(f"new({p['map']}, {p['x']:g}f, {p['z']:g}f)" for p in r['exploration'])
        lines.append(f"            [{r['id']}u] = new([{pts}], {r['playerKills']}, "
                     f"{r['playerMinimumLevel']}, {r['playerMap']}, {r['handInMinimumLevel']}),")
    lines += ["        };", "}", ""]
    (ROOT / "src/Godswar.Server/Domain/World/Content/QuestAdditionalRequirements.Generated.cs").write_text(
        "\n".join(lines), encoding="utf-8")
    types = collections.Counter(t for row in audit for t in row["types"])
    print(json.dumps(dict(selected=len(ids), excluded=len(excluded), types=types,
                          exploration=sum(bool(r['exploration']) for r in requirements),
                          pvp=sum(bool(r['playerKills']) for r in requirements),
                          handin=sum(bool(r['handInMinimumLevel']) for r in requirements)), ensure_ascii=False))


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    main()
