"""Write the captured NPC placements the server should publish.

Sparta's city NPCs are published from the reference capture: the object id, the
appearance word, the position and the facing the original server used. Every
other map's NPCs were written from the client's ini instead, and the difference
is visible in the frame - Athens city's appearance is 0x111 in the capture while
our rows carry 0x11, and most ids are one off - which is why the client does not
treat them as the interactive NPCs they are.

This turns a capture into the placement table the server applies, so a captured
map is written exactly the way Sparta's is.

Usage: python tools/gen_captured_npc_placements.py
"""

import os
import re
import sys

CAPTURE_DIR = r"D:\Godswar Origin\npc-translation"
OUTPUT = (r"D:\Godswar-Reborn-main\src\Godswar.Server\Infrastructure"
          r"\WorldContent\CapturedNpcPlacements.Generated.cs")
# The NPC key is the template key up to its trailing model segment. The scene
# key may itself contain underscores and non-numeric segments
# (`Athens_Newbie_001_MaleVillager2`, `Marathon_All_013_FemMale7`), so a
# `word_digits` model pattern silently drops every NPC on those maps.
MODEL_SUFFIX = re.compile(r"^(?P<key>.+)_(?P<model>[A-Za-z0-9]+)$")

# Captured templates whose npc key is not the template minus its model segment.
# The reference placed the actor that hands out the Marathon_All_006 quests with
# the template `Marathon_006_AthenianWarrior1`, while Quest.xml, NpcName.dat and
# npc_text_templates all call that npc `Marathon_All_006`. Deriving the key
# mechanically would file the placement under `Marathon_006`, which nothing else
# in the data uses, and the quest's own giver would resolve to no npc.
NPC_KEY_OVERRIDE = {
    "Marathon_006_AthenianWarrior1": "Marathon_All_006",
}


def captured_maps():
    found = {}
    for name in os.listdir(CAPTURE_DIR):
        match = re.match(r"captured-npcs-map(\d+)\.txt$", name)
        if not match:
            continue
        rows = []
        with open(os.path.join(CAPTURE_DIR, name), encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("#"):
                    continue
                parts = line.strip().split("|")
                if len(parts) != 6:
                    continue
                object_id, template, low, x, z, facing = parts
                match_model = MODEL_SUFFIX.match(template)
                if match_model is None:
                    continue
                rows.append((
                    NPC_KEY_OVERRIDE.get(
                        template, match_model.group("key")),
                    template,
                    int(object_id),
                    int(low),
                    float(x),
                    float(z),
                    float(facing),
                ))
        if rows:
            found[int(match.group(1))] = sorted(rows)
    return found


def emit(maps):
    lines = [
        "// <auto-generated>",
        "//     Generated by tools/gen_captured_npc_placements.py from the",
        "//     reference capture. Every row is one NPC the reference server",
        "//     actually placed: the object id, appearance word, position and",
        "//     facing it sent. Do not edit by hand.",
        "// </auto-generated>",
        "",
        "namespace Godswar.Server.Infrastructure.WorldContent;",
        "",
        "/// <summary>",
        "/// The NPC placements a capture recorded, per map.",
        "/// </summary>",
        "/// <remarks>",
        "/// Sparta's city NPCs were always published this way; the other maps were",
        "/// written from the client's ini, which uses a different appearance word",
        "/// (Athens city: 0x111 in the capture against 0x11 in the ini) and shifted",
        "/// ids. Applying the captured placement makes those maps' frames identical",
        "/// to the ones the client already accepts elsewhere.",
        "/// </remarks>",
        "internal static class CapturedNpcPlacements",
        "{",
        "    /// <summary>One captured NPC: key, appearance template and placement.</summary>",
        "    internal readonly record struct Placement(",
        "        string NpcKey,",
        "        string TemplateKey,",
        "        uint ObjectId,",
        "        uint AppearanceType,",
        "        float X,",
        "        float Z,",
        "        float Facing);",
        "",
        "    private static readonly Dictionary<string, Placement> All =",
        "        new(StringComparer.Ordinal)",
        "        {",
    ]
    for map_id in sorted(maps):
        lines.append(f"            // map {map_id}: {len(maps[map_id])} NPCs")
        for npc_key, template, object_id, low, x, z, facing in maps[map_id]:
            lines.append(
                f'            ["{npc_key}"] = new("{npc_key}", "{template}", '
                f"{object_id}u, 0x{low:X}u, {x:.4f}f, {z:.4f}f, "
                f"{facing:.4f}f),")
    lines += [
        "        };",
        "",
        "    /// <summary>The captured placements of one map.</summary>",
        "    private static readonly Dictionary<short, Placement[]> ByMap =",
        "        new()",
        "        {",
    ]
    for map_id in sorted(maps):
        lines.append(f"            [(short){map_id}] =")
        lines.append("            [")
        for npc_key, template, object_id, low, x, z, facing in maps[map_id]:
            lines.append(f'                All["{npc_key}"],')
        lines.append("            ],")
    lines += [
        "        };",
        "",
        "    /// <summary>How many NPCs the capture holds for a map.</summary>",
        "    public static int CountFor(short mapId) =>",
        "        ByMap.TryGetValue(mapId, out var placements)",
        "            ? placements.Length",
        "            : 0;",
        "",
        "    /// <summary>Whether the reference capture placed any NPC on a map.</summary>",
        "    public static bool HasCaptureFor(short mapId) =>",
        "        ByMap.ContainsKey(mapId);",
        "",
        "    /// <summary>The NPC keys the reference capture placed on a map.</summary>",
        "    public static IReadOnlySet<string> CapturedKeysFor(short mapId)",
        "    {",
        "        if (!ByMap.TryGetValue(mapId, out var placements))",
        "        {",
        "            return EmptyKeys;",
        "        }",
        "",
        "        var keys = new HashSet<string>(placements.Length, StringComparer.Ordinal);",
        "        foreach (var placement in placements)",
        "        {",
        "            keys.Add(placement.NpcKey);",
        "        }",
        "",
        "        return keys;",
        "    }",
        "",
        "    private static readonly HashSet<string> EmptyKeys =",
        "        new(StringComparer.Ordinal);",
        "",
        "    /// <summary>The captured placement of one NPC, when it was captured.</summary>",
        "    public static bool TryFind(string npcKey, out Placement placement) =>",
        "        All.TryGetValue(npcKey, out placement);",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    maps = captured_maps()
    if not maps:
        raise SystemExit(f"no captured-npcs-map*.txt under {CAPTURE_DIR}")
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(emit(maps))
    print(f"wrote {OUTPUT}")
    for map_id in sorted(maps):
        llows = {}
        for _, _, _, low, _, _, _ in maps[map_id]:
            llows[low] = llows.get(low, 0) + 1
        print(f"  map {map_id}: {len(maps[map_id])} NPCs, "
              f"appearance { {hex(k): v for k, v in sorted(llows.items())} }")
    return 0


if __name__ == "__main__":
    sys.exit(main())
